/*** TEMPLATE FOR GENERATING - ngComponents.js - WHICH WILL CONTAIN ALL AVAILABLE COMPONENTS ***/

// ATOMS:
{ATOMS}

// MOLECULES:
{MOLECULES}

// ORGANISMS:
{ORGANISMS}

// TEMPLATES:
{TEMPLATES}