/*** AUTO-GENERATED BY GULP ***/

angular.module("lnPatterns").run(["$templateCache", function($templateCache) {$templateCache.put("lnPatterns/templates/patterns/template.html","<!-- AUTO-GENERATED BY GULP -->\r\n\r\n");}]);